spring.application.name=assessment-platform
spring.config.import=optional:file:.env[.properties]

jwt_secret_key=${JWT_SECRET_KEY}

spring.datasource.url=jdbc:mysql://mysql-smart-hire-spring-boot-smarthire-assessment-platform.l.aivencloud.com:22155/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${MYSQL_PASSWORD_AivenIO}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
